title: Peermit.com
email: info@peermit.com
description: >
  Peermit.com provides the first of its kind second factor
  authentication (2FA) service for BitShares to secure your accounts and
  funds on the blockchain without counterparty-risk. You are always in
  control!
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://peermit.com" # the base hostname & protocol for your site
github_username:  peermit
markdown: kramdown
